In [4]:
import pandas as pd
import numpy as np

/Users/kyo/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/Users/kyo/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


## Analytical method

In [5]:
df = pd.read_csv('GradIOsample6.csv', header=None)

In [6]:
data = df.values

In [7]:
data.shape

(5666, 5)

In [8]:
y = data[:,0]
y.shape

(5666,)

In [9]:
x1 = data[:,1:5]

In [10]:
x1.shape

(5666, 4)

In [11]:
n = data.shape[0]

In [13]:
X = np.hstack([np.ones((n,1)), x1])

In [14]:
X.shape

(5666, 5)

In [15]:
K = data.shape[1]

In [16]:
X[:,1] = X[:,1]/10
X[:,2] = X[:,2]/1000

In [17]:
beta = np.linalg.inv((X.T @ X))@X.T @ y
beta

array([ 9.49094879e+00, -1.07746273e+00,  3.04095581e+01, -3.34891611e-04,
        2.50034965e-01])

## Numerical Method

In [18]:
import scipy.optimize

In [19]:
X[1]

array([1.000e+00, 1.000e-01, 7.100e-02, 5.041e+03, 3.000e+00])

In [48]:
X[1].shape

(5,)

In [49]:
def sum_theta(theta):
    sum = 0
    for i in range(n):
        sum += (y[i] - np.dot(X[i], theta))**2
    return sum

In [43]:
theta_0 = np.ones((5,1))

In [50]:
theta_opt = scipy.optimize.minimize(sum_theta, x0=theta_0)

In [51]:
theta_opt

      fun: 2720.308106870884
 hess_inv: array([[ 1.25258525e-03, -2.33637740e-03, -1.09631117e-03,
        -1.17237040e-07, -3.26551687e-04],
       [-2.33637740e-03,  3.51950081e-02,  5.01066019e-03,
         8.81563228e-08,  1.37484760e-05],
       [-1.09631117e-03,  5.01066019e-03,  1.24639459e-03,
         9.53560143e-08,  2.20986393e-04],
       [-1.17237040e-07,  8.81563228e-08,  9.53560143e-08,
         4.67774232e-11,  4.29812530e-10],
       [-3.26551687e-04,  1.37484760e-05,  2.20986393e-04,
         4.29812530e-10,  1.43157218e-04]])
      jac: array([-0.00524902,  0.00073242, -0.00363159, -0.09710693, -0.0012207 ])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 747
      nit: 13
     njev: 105
   status: 2
  success: False
        x: array([ 9.49025158e+00, -1.07746690e+00,  3.04459250e+01, -3.35311243e-04,
        2.50036080e-01])

In [52]:
X[1]

array([1.000e+00, 1.000e-01, 7.100e-02, 5.041e+03, 3.000e+00])

In [55]:
X[1][:, np.newaxis].shape

(5, 1)

In [56]:
X[1][:, np.newaxis]

array([[1.000e+00],
       [1.000e-01],
       [7.100e-02],
       [5.041e+03],
       [3.000e+00]])